apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: fluxcd-demo-app
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: fluxcd-demo-app-auth
  url: https://github.com/pavan-baloji/fluxcd-demo-app

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fluxcd-demo-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-demo-app
---
apiVersion: v1
kind: Secret
metadata:
  name: fluxcd-demo-app-auth
  namespace: flux-system
stringData:
  password: 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
  username: pavanbaloji@gmail.com