---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: fluxcd-demo-app-helm
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: fluxcd-demo-repo-auth
  url: https://github.com/pavan-baloji/fluxcd-demo-app-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluxcd-demo-app-helmrelease
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: fluxcd-demo-app-helm
  interval: 10s
  targetNamespace: demo-app
  values:
    fullnameOverride: ""
    image:
      pullPolicy: Always
      repository: siddharth67/block-buster-dev:7.5.0
      tag: ""
    imagePullSecrets: []
    labels:
      app:
        env: uat
        name: bb-app
        version: 7.x.x
    nameOverride: ""
    namespace:
      name: demo-app
    replicaCount: 1
    service:
      port: 80
      targetPort: 80
      type: LoadBalancer