---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: fluxcd-demo-app-helm
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: fluxcd-demo-repo-auth
  url: https://github.com/pavan-baloji/fluxcd-demo-app-helm

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fluxcd-demo-app-helm
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./helm-chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd-demo-app-helm
  targetNamespace: demo-app
